### ISSUE TITLE
[Announcement] WebSockets disabled in WebListener for v1

### ISSUE THREAD

**Issue by Tratcher** [aspnet/WebSockets#64]
WebSockets are not on the roadmap for ASP.NET 5 v1. This has the following implications:
A) WebSockets have been disabled in Microsoft.AspNet.Server.WebListener. Opaque upgrades still work so Microsoft.AspNet.WebSockets.Server middleware can still be used to add the functionality.
B) Microsoft.Net.WebSockets has been renamed to Microsoft.Net.WebSockets.Server and refactored to be an optional package that can be added on top of Microsoft.Net.Http.Server. This is for developers that are using WebListener independent of Asp.Net.
C)  Microsoft.Net.WebSockets.Server and  Microsoft.AspNet.WebSockets.\* will not be shipped to nuget.org with the final 1.0 release. Pre-releases will continue to be available on myget.org.

We will revisit WebSockets after v1.

**Comment by cherrydev** [comment]
I assume that this means that SignalR will not make use of WebSockets anymore unless the WebSockets middleware is explicitly added in?  Is there a discussion thread somewhere where I might get an idea of why it's been removed from the roadmap?

**Comment by dmccaffery** [comment]
@cherrydev SignalR and WebSockets has been on the chopping block for quite some time. I do believe that SignalR using long polling will be an option, but I could be wrong on that.

**Comment by benaadams** [comment]
@cherrydev at a guess because WebSockets without the middleware is specifically tied to WebListener on a Windows Server version 2012 or above; and its another code path to maintain. Whereas the middleware works cross platform on all operating systems and all server versions? Also the non-middleware version causes memory fragmentation between pinned buffers; and performance degradation unless you jump though a few hoops.

**Comment by cherrydev** [comment]
I guess I'm not really clear what the implications of this are.  There are two separate implementations of WebSockets?  One for WebListener Windows Server 2012 and a middleware one that works with all servers?  And the WebListener one is going to be cut entirely, and the middleware one will still exist but won't be published as a 1.0 release?

**Comment by Tratcher** [comment]
@cherrydev @dmccaffery Check the roadmap: https://github.com/aspnet/Home/wiki/Roadmap#future-work, none of SignalR will be included in this release.

@benaadams All WebSockets implementations are being excluded from v1 because we won't be able to finish the perf, stress, and functional testing in time. The middleware is easy to add in from myget, but it's not as easy to dynamically extend Microsoft.AspNet.WebSockets.Server that way so we had to completely disabled it. We don't plan to delete either implementation. Note the WebListener implementation requires Win8/2008R2+, not 2012+.

**Comment by cherrydev** [comment]
Thanks for the pointer.  So it's just a matter of priorities and time, not that SignalR and WebSockets are being considered to drop from the platform.

**Comment by dmccaffery** [comment]
Sweet. Thanks for the additional info -- I saw that roadmap some months ago and new SignalR wasn't going to happen for v1, but that's not that big of an issue -- there are plenty of ways to work around it for those that need it.

**Comment by Tratcher** [comment]
Right, we'll get back to them once we get the base platform shipped.

**Comment by jods4** [comment]
I am not totally clear with the references to the WebSocket packages still being available on myget.

Right now I have a web app built on top of RC1 that uses WebSockets. Not SignalR -- because I saw it was out of the v1 -- but WebSockets directly (simple stuff).

Will there be a way to keep WebSockets working when upgrading to RC2, by referencing the myget package? (I understand this is not final, you haven't done perf work, etc.)

**Comment by Flavien** [comment]
Is that supported on Kestrel though?

**Comment by benaadams** [comment]
@Flavien yep
@jods4 I'm running with the middleware on RC2 (dev)

**Comment by Daniel15** [comment]
Minor typo in the title of this issue: "Annoucement" should be "Annou**n**cement" :stuck_out_tongue:

**Comment by gdoron** [comment]
@Tratcher Is there an example of how to use in an RC1-Final project?

**Comment by Tratcher** [comment]
@gdoron Does this help? https://github.com/aspnet/WebSockets/blob/1.0.0-rc1/test/AutobahnTestServer/Startup.cs#L21-L36

**Comment by gdoron** [comment]
@Tratcher Woohoo that was fast.
Yes, it most definitely helps, now I just need to find out how to use it...

    sp_rename gdoron, Christopher Columbus
:laughing: 
Thanks! :+1:

**Comment by gdoron** [comment]
@Tratcher Took me a while, but I managed to integrate redis and WebSockets messaging over a cluster of servers.
Which makes me think, since it worked so nicely, why isn't it in the RC? Do I need to fear from performance issues? crashes? we plan to go live-production with our application when RC2 will be released... :fearful: Do you think it's a bad idea adding WebSockets to it (it's not a mandatory feature)?

Thanks a lot for hint and help!

**Comment by Tratcher** [comment]
While we do have WebSockets working, we don't have the resources to do extended testing, performance, and stress work on it until after 1.0. That's why we're not including it. Use it at your own risk.

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.”
