### ISSUE TITLE
subprotocol is not returned in WebSocket Upgrade / Accept Response

### ISSUE THREAD

**Issue by rposener** [aspnet/WebSockets#79]
the following JS:
 `var exampleSocket = new WebSocket("ws://" + window.location.host, "test");` 
 when accepted by:
 `WebSocket webSocket = await httpContext.WebSockets.AcceptWebSocketAsync("test");` 
 does not include the header value:
 `Sec-WebSocket-Protocol:test`  

even though it should per spec.

**Comment by muratg** [comment]
Tentatively putting this in 1.0.0. We'll investigate after RC2 ships.

**Comment by tmds** [comment]
@rposener what server are you using?

**Comment by rposener** [comment]
As best I understand it's kestral hosted within IISExpress (project is targeting dnx451 and dnxcore50) currently for rc1-update2

**Comment by tmds** [comment]
What should happen:
the value you give in AcceptWebSocketAsync should be set in the WebSocketAccept context [here](https://github.com/aspnet/HttpAbstractions/blob/3a97a6bdfdcc3787bf4b68cecdf277588de5ee76/src/Microsoft.AspNetCore.Http/Internal/DefaultWebSocketManager.cs#L60).
Then read from the context [here](https://github.com/aspnet/WebSockets/blob/0f9e4eba024078d2b0b2f1efb70a594b9ee70d0c/src/Microsoft.AspNetCore.WebSockets.Server/WebSocketMiddleware.cs#L97), passed on to [GenerateResponseHeaders](https://github.com/aspnet/WebSockets/blob/0f9e4eba024078d2b0b2f1efb70a594b9ee70d0c/src/Microsoft.AspNetCore.WebSockets.Server/WebSocketMiddleware.cs#L117) to end up in the header IEnumerable [here](https://github.com/aspnet/WebSockets/blob/0f9e4eba024078d2b0b2f1efb70a594b9ee70d0c/src/Microsoft.AspNetCore.WebSockets.Protocol/HandshakeHelpers.cs#L79), which then becomes part of the response headers [here](https://github.com/aspnet/WebSockets/blob/0f9e4eba024078d2b0b2f1efb70a594b9ee70d0c/src/Microsoft.AspNetCore.WebSockets.Server/WebSocketMiddleware.cs#L120).

Stepping through [AcceptAsync](https://github.com/aspnet/WebSockets/blob/0f9e4eba024078d2b0b2f1efb70a594b9ee70d0c/src/Microsoft.AspNetCore.WebSockets.Server/WebSocketMiddleware.cs#L87) may give you an idea of what the issue is. If you check out [Microsoft.AspNetCore.WebSockets.Server](https://github.com/aspnet/WebSockets/tree/0f9e4eba024078d2b0b2f1efb70a594b9ee70d0c/src/Microsoft.AspNetCore.WebSockets.Server) and add it to your 'src' folder, you should be able to set a breakpoint in that method.

**Comment by Tratcher** [comment]
Does it work if you run Kestrel directly without IISExpress?

**Comment by rposener** [comment]
Yes, works fine once IISExpress is removed from the mix.  Is there a way to allow that to pass through?

**Comment by Tratcher** [comment]
We'll have to investigate. @pan-wang, can you take a look?

**Comment by muratg** [comment]
@anurse Does SignalR use subprotocol in websockets?

**Comment by Tratcher** [comment]
This issue was moved to aspnet/IISIntegration#240
